# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  if Vagrant.has_plugin? "vagrant-vbguest"
    config.vbguest.no_install  = true
    config.vbguest.auto_update = false
    config.vbguest.no_remote   = true
  end

    config.vm.synced_folder "Compartida/", "/home/vagrant/shared"

  config.vm.define :mvHaproxy do |mvHaproxy|
    mvHaproxy.vm.box = "bento/ubuntu-20.04"
    mvHaproxy.vm.network :private_network, ip: "192.168.90.2"
    mvHaproxy.vm.hostname = "mvHaproxy"
    mvHaproxy.vm.provision "shell", path: "aprov_haproxy.sh"  
  end

  config.vm.define :servidorWebA do |servidorWebA|
    servidorWebA.vm.box = "bento/ubuntu-20.04"
    servidorWebA.vm.network :private_network, ip: "192.168.90.3"
    servidorWebA.vm.hostname = "servidorWebA"
    servidorWebA.vm.provision "shell", path: "aprov_servidorA.sh"
  end

  config.vm.define :servidorWebB do |servidorWebB|
    servidorWebB.vm.box = "bento/ubuntu-20.04"
    servidorWebB.vm.network :private_network, ip: "192.168.90.4"
    servidorWebB.vm.hostname = "servidorWebB"
    servidorWebB.vm.provision "shell", path: "aprov_servidorB.sh"
  end
end
